// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj6E2i5GRI0HN6ZPufrl2tgIJErfUni5Q',
    appId: '1:231987321719:android:cff99366f31f86dd695f72',
    messagingSenderId: '231987321719',
    projectId: 'thriftapp-e452b',
    storageBucket: 'thriftapp-e452b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFGPow5ZAlwAOUWhwtGHppGaAvt6iNEfU',
    appId: '1:231987321719:ios:044ccd0df4047fb2695f72',
    messagingSenderId: '231987321719',
    projectId: 'thriftapp-e452b',
    storageBucket: 'thriftapp-e452b.firebasestorage.app',
    androidClientId: '231987321719-r2ds8u91u0fmlj9g0ekr17fpq7m2parp.apps.googleusercontent.com',
    iosClientId: '231987321719-a61uhg8bhglndpdc00d3n0iaocstke5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.thriftApp',
  );
}
